# Generated by Django 3.2.14 on 2022-07-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='hazard',
            options={'ordering': ['status', 'created_on'], 'verbose_name_plural': 'Hazards'},
        ),
        migrations.AlterModelOptions(
            name='risk',
            options={'verbose_name_plural': 'Risks'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
