# Generated by Django 3.2.14 on 2022-07-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0003_auto_20220730_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
