# Generated by Django 3.2.14 on 2022-08-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0007_auto_20220806_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
