# Generated by Django 3.2.14 on 2022-08-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0010_remove_hazard_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
