# Generated by Django 3.2.14 on 2022-08-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0011_hazard_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='risk',
            options={'ordering': ['id'], 'verbose_name_plural': 'Risks'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['id'], 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterField(
            model_name='hazard',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='risk',
            name='level',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
