# Generated by Django 3.2.14 on 2022-08-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0012_auto_20220824_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
