# Generated by Django 3.2.14 on 2022-08-27 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0015_auto_20220827_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='risk',
            name='level',
            field=models.CharField(max_length=6, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
